services:
  notifications:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP=notifications
    ports:
      - '3006-3009:3001'
    environment:
      - NODE_ENV=production
      - KAFKA_BROKER=kafka:9092
      - DATABASE_URL=postgresql://user:password@postgres:5432/orders
    networks:
      - kafka-network
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
networks:
  kafka-network:
